//! The TypeScript the dashboard compiles against, generated from the Rust
//! types and constants it mirrors, and a contract test that fails when the
//! committed `web/src/lib/api.gen.ts` drifts from them.
//!
//! Why a checked-in file plus a test, rather than a build step: the release
//! build bakes `web/` before cargo runs (`bun run build`, then
//! `cargo build --release`), and the web toolchain must not need cargo. So
//! the generated file is committed like any source, and `cargo test` (every
//! gate runs it) refuses a stale copy. Regenerate with:
//!
//! ```text
//! APB_WRITE_TS=1 cargo test -p apb-server --lib ts_contract
//! ```
//!
//! Types come from `ts-rs` derives (honouring the serde attributes, so the
//! wire shape and the declaration cannot disagree); constants come from the
//! core items that own them.

use ts_rs::{Config, TS};

const GENERATED: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../web/src/lib/api.gen.ts");

fn ts_string_array(items: &[&str]) -> String {
    let quoted: Vec<String> = items.iter().map(|s| format!("'{s}'")).collect();
    format!("[{}] as const", quoted.join(", "))
}

/// The whole generated module.
fn render() -> String {
    // Timestamps are u128 milliseconds on the Rust side and plain JSON
    // numbers on the wire.
    let cfg = Config::new().with_large_int("number");
    let decls = [
        apb_engine::state::RunStatus::decl(&cfg),
        apb_engine::state::NodeStatus::decl(&cfg),
        apb_engine::progress::WaitingKind::decl(&cfg),
        apb_engine::progress::PendingQuestion::decl(&cfg),
        apb_engine::progress::PendingReview::decl(&cfg),
        apb_engine::progress::PendingSupervisor::decl(&cfg),
        apb_engine::progress::ProgressSummary::decl(&cfg),
        apb_engine::run_view::ChildRun::decl(&cfg),
        apb_engine::RunSummary::decl(&cfg),
        crate::routes::runs::RunListEntry::decl(&cfg),
        crate::routes::runs::RunDetail::decl(&cfg),
    ];
    let mut out = String::from(
        "// GENERATED by apb-server's ts_contract test from the Rust types and\n\
         // constants. Do not edit: change the Rust side and run\n\
         // `APB_WRITE_TS=1 cargo test -p apb-server --lib ts_contract`.\n\n\
         import type { PlaybookEdge, PlaybookNode, WfEvent, WfLayout } from './types'\n",
    );
    for d in decls {
        out.push_str("\nexport ");
        out.push_str(&d);
        out.push('\n');
    }
    use apb_core::schema;
    out.push_str(&format!(
        "\n/** The playbook schema this apb writes. */\nexport const CURRENT_SCHEMA = {}\n",
        schema::CURRENT_SCHEMA
    ));
    out.push_str(&format!(
        "\n/** Every node `type` tag. */\nexport const NODE_TYPES = {}\nexport type NodeType = (typeof NODE_TYPES)[number]\n",
        ts_string_array(&schema::NODE_TYPES)
    ));
    out.push_str(&format!(
        "\n/** The decisions a human_review gate without options offers. */\nexport const DEFAULT_REVIEW_OPTIONS = {}\n",
        ts_string_array(&schema::DEFAULT_REVIEW_OPTIONS)
    ));
    out.push_str(&format!(
        "\n/** Starter document for a new playbook. */\nexport const NEW_PLAYBOOK_TEMPLATE = {}\n",
        serde_json::to_string(&schema::new_playbook_template()).expect("a string serializes")
    ));
    out
}

#[test]
fn generated_typescript_is_current() {
    let rendered = render();
    if std::env::var_os("APB_WRITE_TS").is_some() {
        std::fs::write(GENERATED, &rendered).expect("write api.gen.ts");
        return;
    }
    let committed = std::fs::read_to_string(GENERATED).unwrap_or_default();
    assert!(
        committed == rendered,
        "web/src/lib/api.gen.ts is out of date with the Rust types it mirrors; \
         regenerate it with `APB_WRITE_TS=1 cargo test -p apb-server --lib ts_contract`"
    );
}
