//! The TypeScript the dashboard compiles against, generated from the Rust
//! types and constants it mirrors, and a contract test that fails when the
//! committed `web/src/lib/api.gen.ts` drifts from them.
//!
//! Why a checked-in file plus a test, rather than a build step: the release
//! build bakes `web/` before cargo runs (`bun run build`, then
//! `cargo build --release`), and the web toolchain must not need cargo. So
//! the generated file is committed like any source, and `cargo test` (every
//! gate runs it) refuses a stale copy. Regenerate with:
//!
//! ```text
//! APB_WRITE_TS=1 cargo test -p apb-server --lib ts_contract
//! ```
//!
//! Types come from `ts-rs` derives (honouring the serde attributes, so the
//! wire shape and the declaration cannot disagree); constants come from the
//! core items that own them.

use ts_rs::{Config, TS};

const TYPES_FILE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../web/src/lib/api.gen.ts");
/// Constants live in their own import-free module so the Vite config (a node
/// program with its own module resolution) can read them too.
const CONSTS_FILE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../web/src/lib/consts.gen.ts"
);

const HEADER: &str = "// GENERATED by apb-server's ts_contract test from the Rust types and\n\
     // constants. Do not edit: change the Rust side and run\n\
     // `APB_WRITE_TS=1 cargo test -p apb-server --lib ts_contract`.\n";

fn ts_string_array(items: &[&str]) -> String {
    let quoted: Vec<String> = items.iter().map(|s| format!("'{s}'")).collect();
    format!("[{}] as const", quoted.join(", "))
}

/// The generated types module.
fn render_types() -> String {
    // Timestamps are u128 milliseconds on the Rust side and plain JSON
    // numbers on the wire.
    let cfg = Config::new().with_large_int("number");
    let decls = [
        // 0.23.0 run outcome blocks (C1, C7).
        apb_engine::event::CommittedArtifact::decl(&cfg),
        apb_engine::run_outcome::NodeCommits::decl(&cfg),
        apb_engine::run_outcome::GoalCriterionResult::decl(&cfg),
        apb_engine::run_outcome::RunGoal::decl(&cfg),
        apb_engine::state::RunStatus::decl(&cfg),
        apb_engine::state::NodeStatus::decl(&cfg),
        apb_engine::progress::WaitingKind::decl(&cfg),
        apb_engine::progress::PendingQuestion::decl(&cfg),
        apb_engine::event::ReviewRecommendation::decl(&cfg),
        apb_engine::progress::PendingReview::decl(&cfg),
        apb_engine::progress::PendingSupervisor::decl(&cfg),
        apb_engine::progress::ProgressSummary::decl(&cfg),
        apb_engine::run_view::ChildRun::decl(&cfg),
        apb_engine::run_view::RunUsage::decl(&cfg),
        apb_engine::run_view::RunDecisions::decl(&cfg),
        apb_engine::run_view::RunDecisionUse::decl(&cfg),
        apb_core::agent_output::UsageSource::decl(&cfg),
        apb_core::agent_output::AgentUsage::decl(&cfg),
        apb_engine::RunSummary::decl(&cfg),
        crate::routes::runs::RunListEntry::decl(&cfg),
        crate::routes::runs::RunDetail::decl(&cfg),
        apb_core::versioning::TrashEntry::decl(&cfg),
        apb_core::versioning::RestoredPlaybook::decl(&cfg),
        crate::routes::trash::TrashListEntry::decl(&cfg),
        apb_core::trust::Kind::decl(&cfg),
        apb_core::trust::OriginKind::decl(&cfg),
        apb_core::trust::TrustEntry::decl(&cfg),
        crate::routes::trust::TrustRevoked::decl(&cfg),
    ];
    let mut out = format!(
        "{HEADER}\nimport type {{ PlaybookEdge, PlaybookNode, WfEvent, WfLayout }} from './types'\n"
    );
    for d in decls {
        out.push_str("\nexport ");
        out.push_str(&d);
        out.push('\n');
    }
    out
}

/// The generated constants module (no imports).
fn render_consts() -> String {
    use apb_core::schema;
    let mut out = String::from(HEADER);
    out.push_str(&format!(
        "\n/** The playbook schema this apb writes. */\nexport const CURRENT_SCHEMA = {}\n",
        schema::CURRENT_SCHEMA
    ));
    out.push_str(&format!(
        "\n/** Every node `type` tag. */\nexport const NODE_TYPES = {}\nexport type NodeType = (typeof NODE_TYPES)[number]\n",
        ts_string_array(&schema::NODE_TYPES)
    ));
    out.push_str(&format!(
        "\n/** The decisions a human_review gate without options offers. */\nexport const DEFAULT_REVIEW_OPTIONS = {}\n",
        ts_string_array(&schema::DEFAULT_REVIEW_OPTIONS)
    ));
    out.push_str(&format!(
        "\n/** The dashboard's default port (the dev server proxies to it). */\nexport const DEFAULT_PORT = {}\n",
        apb_core::config::DEFAULT_PORT
    ));
    out.push_str(&format!(
        "\n/** Legacy agent ids and the built-in agent each stands for. */\nexport const AGENT_ALIASES: Readonly<Record<string, string>> = {{ {} }}\n",
        apb_core::detect::BUILTIN_ALIASES
            .iter()
            .map(|(alias, id)| format!("'{alias}': '{id}'"))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str(&format!(
        "\n/** Starter document for a new playbook. */\nexport const NEW_PLAYBOOK_TEMPLATE = {}\n",
        serde_json::to_string(&schema::new_playbook_template()).expect("a string serializes")
    ));
    out
}

#[test]
fn generated_typescript_is_current() {
    for (path, rendered) in [(TYPES_FILE, render_types()), (CONSTS_FILE, render_consts())] {
        if std::env::var_os("APB_WRITE_TS").is_some() {
            std::fs::write(path, &rendered).expect("write the generated module");
            continue;
        }
        let committed = std::fs::read_to_string(path).unwrap_or_default();
        assert!(
            committed == rendered,
            "{path} is out of date with the Rust it mirrors; \
             regenerate it with `APB_WRITE_TS=1 cargo test -p apb-server --lib ts_contract`"
        );
    }
}
