version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: bun
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-dependencies:
        patterns:
          - "*"
