name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: Breaking Changes
    labels: ['breaking']
  - title: New Features
    labels: ['enhancement']
  - title: Bug Fixes
    labels: ['bug']
  - title: Documentation
    labels: ['documentation']
  - title: Dependencies
    labels: ['dependencies']
    collapse-after: 5
  - title: Internal
    labels: ['internal', 'chore']

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
