//! Static contract of the repository's GitHub workflows (the release path).
//!
//! These workflows never run under `cargo test`, and a mistake in them only
//! shows up on a tag push, when a release is already on its way out. The checks
//! parse the YAML and assert the three release guarantees directly: every
//! third-party action is pinned to a commit, publication waits for a green test
//! gate, and published artifacts carry a build-provenance attestation.
//!
//! `release.yml` is generated by dist from `dist-workspace.toml` and
//! `.github/build-setup.yml`; fix a failure there and run `dist generate`,
//! never by hand-editing the generated file.

use std::path::{Path, PathBuf};

use serde_yaml_ng::Value;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repo root")
}

fn load(path: &Path) -> Value {
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_yaml_ng::from_str(&text).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

/// Every workflow file plus the dist build-setup steps spliced into release.yml.
fn workflow_files() -> Vec<PathBuf> {
    let root = repo_root();
    let mut files: Vec<PathBuf> = std::fs::read_dir(root.join(".github/workflows"))
        .expect("workflows dir")
        .map(|e| e.expect("dir entry").path())
        .filter(|p| matches!(p.extension().and_then(|x| x.to_str()), Some("yml" | "yaml")))
        .collect();
    files.push(root.join(".github/build-setup.yml"));
    files.sort();
    files
}

fn collect_uses(value: &Value, out: &mut Vec<String>) {
    match value {
        Value::Mapping(map) => {
            for (k, v) in map {
                if k.as_str() == Some("uses")
                    && let Some(s) = v.as_str()
                {
                    out.push(s.to_string());
                }
                collect_uses(v, out);
            }
        }
        Value::Sequence(seq) => seq.iter().for_each(|v| collect_uses(v, out)),
        _ => {}
    }
}

fn is_commit_sha(r: &str) -> bool {
    r.len() == 40
        && r.bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase())
}

#[test]
fn every_third_party_action_is_pinned_to_a_full_commit_sha() {
    let mut unpinned = Vec::new();
    for file in workflow_files() {
        let mut uses = Vec::new();
        collect_uses(&load(&file), &mut uses);
        for u in uses {
            // Local reusable workflows are part of this commit already.
            if u.starts_with("./") {
                continue;
            }
            let pinned = u.rsplit_once('@').is_some_and(|(_, r)| is_commit_sha(r));
            if !pinned {
                unpinned.push(format!("{}: {u}", file.display()));
            }
        }
    }
    assert!(
        unpinned.is_empty(),
        "actions must be pinned to a 40-char commit SHA (tag in a comment):\n{}",
        unpinned.join("\n")
    );
}

struct Release {
    jobs: serde_yaml_ng::Mapping,
}

impl Release {
    fn load() -> Self {
        let doc = load(&repo_root().join(".github/workflows/release.yml"));
        let jobs = doc
            .get("jobs")
            .and_then(Value::as_mapping)
            .expect("release.yml jobs")
            .clone();
        Self { jobs }
    }

    fn steps(job: &Value) -> Vec<&Value> {
        job.get("steps")
            .and_then(Value::as_sequence)
            .map(|s| s.iter().collect())
            .unwrap_or_default()
    }

    /// The job that creates the GitHub Release.
    fn publisher(&self) -> (String, &Value) {
        self.jobs
            .iter()
            .find(|(_, job)| {
                Self::steps(job).iter().any(|s| {
                    s.get("run")
                        .and_then(Value::as_str)
                        .is_some_and(|r| r.contains("gh release create"))
                })
            })
            .map(|(k, v)| (k.as_str().expect("job id").to_string(), v))
            .expect("a job runs `gh release create`")
    }

    /// The job that calls the repository test gate workflow.
    fn gate(&self) -> (String, &Value) {
        self.jobs
            .iter()
            .find(|(_, job)| {
                job.get("uses").and_then(Value::as_str) == Some("./.github/workflows/test-gate.yml")
            })
            .map(|(k, v)| (k.as_str().expect("job id").to_string(), v))
            .expect("release.yml calls ./.github/workflows/test-gate.yml")
    }
}

fn needs(job: &Value) -> Vec<String> {
    match job.get("needs") {
        Some(Value::String(s)) => vec![s.clone()],
        Some(Value::Sequence(seq)) => seq
            .iter()
            .filter_map(|v| v.as_str().map(str::to_string))
            .collect(),
        _ => Vec::new(),
    }
}

fn condition(job: &Value) -> String {
    job.get("if")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string()
}

#[test]
fn a_release_is_published_only_after_the_test_gate_succeeded() {
    let release = Release::load();
    let (gate_id, gate) = release.gate();
    let (publisher_id, publisher) = release.publisher();

    // The publisher waits for the gate and its condition inspects the gate's
    // result: `always()` in that condition would otherwise run it after a
    // failed gate.
    assert!(
        needs(publisher).contains(&gate_id),
        "{publisher_id} must need {gate_id}"
    );
    let cond = condition(publisher);
    assert!(
        cond.contains(&format!("needs.{gate_id}.result == 'success'")),
        "{publisher_id}'s condition must require {gate_id} to succeed: {cond}"
    );
    assert!(
        cond.contains("needs.plan.result == 'success'")
            && cond.contains("needs.plan.outputs.publishing == 'true'"),
        "{publisher_id} must only run on a successful publishing plan: {cond}"
    );

    // The publisher's condition accepts a `skipped` gate (dist's generated
    // form), so the gate itself must not be skippable on a publishing run:
    // it depends on nothing but the plan, and its own condition is true
    // whenever the plan says this run publishes.
    assert_eq!(
        needs(gate),
        vec!["plan".to_string()],
        "{gate_id} must depend only on plan, or a failure upstream would skip it"
    );
    let gate_cond = condition(gate);
    assert!(
        gate_cond.is_empty() || gate_cond.contains("needs.plan.outputs.publishing == 'true' ||"),
        "{gate_id} must run on every publishing run: {gate_cond}"
    );
}

#[test]
fn the_release_gate_runs_on_every_shipped_os() {
    // The build legs only build, so the gate alone carries the per-platform
    // checks. Its matrix must keep a Linux leg and a leg on each macOS runner
    // dist builds on (dist 0.32 defaults: macos-14 for arm, macos-15-intel
    // for Intel); dropping one would let a platform-only break ship.
    let doc = load(&repo_root().join(".github/workflows/test-gate.yml"));
    let gate = doc
        .get("jobs")
        .and_then(|j| j.get("gate"))
        .expect("test-gate.yml has a `gate` job");
    let legs = gate
        .get("strategy")
        .and_then(|s| s.get("matrix"))
        .and_then(|m| m.get("include"))
        .and_then(Value::as_sequence)
        .expect("gate matrix include list");
    let runners: Vec<&str> = legs
        .iter()
        .filter_map(|l| l.get("runner").and_then(Value::as_str))
        .collect();
    assert!(
        runners.iter().any(|r| r.starts_with("ubuntu-")),
        "no Linux gate leg: {runners:?}"
    );
    for want in ["macos-14", "macos-15-intel"] {
        assert!(
            runners.contains(&want),
            "no gate leg on {want}: {runners:?}"
        );
    }

    // Every tag must ship with its reviewed release notes.
    let notes_checked = Release::steps(gate).iter().any(|s| {
        s.get("run")
            .and_then(Value::as_str)
            .is_some_and(|r| r.contains("docs/release-notes/${GITHUB_REF_NAME}.md"))
    });
    assert!(notes_checked, "the gate must check the tag's release notes");
}

#[test]
fn published_artifacts_get_a_build_provenance_attestation_first() {
    let release = Release::load();
    let (publisher_id, publisher) = release.publisher();
    let steps = Release::steps(publisher);

    let position = |pred: &dyn Fn(&Value) -> bool| steps.iter().position(|s| pred(s));
    let attest = position(&|s| {
        s.get("uses")
            .and_then(Value::as_str)
            .is_some_and(|u| u.starts_with("actions/attest@"))
    })
    .unwrap_or_else(|| panic!("{publisher_id} has no actions/attest step"));
    let create = position(&|s| {
        s.get("run")
            .and_then(Value::as_str)
            .is_some_and(|r| r.contains("gh release create"))
    })
    .expect("gh release create step");
    assert!(attest < create, "attestation must precede the release");

    let subject = steps[attest]
        .get("with")
        .and_then(|w| w.get("subject-path"))
        .and_then(Value::as_str)
        .unwrap_or_default();
    assert!(
        subject.lines().any(|l| l.trim() == "artifacts/*"),
        "the attestation must cover every uploaded artifact, got {subject:?}"
    );

    let perms = publisher.get("permissions").expect("job permissions");
    for (key, want) in [("id-token", "write"), ("attestations", "write")] {
        assert_eq!(
            perms.get(key).and_then(Value::as_str),
            Some(want),
            "{publisher_id} needs {key}: {want} to attest"
        );
    }
}
