// GENERATED by apb-server's ts_contract test from the Rust types and
// constants. Do not edit: change the Rust side and run
// `APB_WRITE_TS=1 cargo test -p apb-server --lib ts_contract`.

import type { PlaybookEdge, PlaybookNode, WfEvent, WfLayout } from './types'

export type CommittedArtifact = { sha: string, subject: string, };

export type NodeCommits = { node: string, 
/**
 * `HEAD` before the node ran.
 */
before: string, 
/**
 * `HEAD` after it.
 */
after: string, 
/**
 * Newest first, at most 50.
 */
commits: Array<CommittedArtifact>, 
/**
 * Commits past the listed ones.
 */
omitted: number, };

export type GoalCriterionResult = { index: number, description: string, 
/**
 * `script`, `marker` or `manual`.
 */
check: string, 
/**
 * `passed`, `failed`, `error`, `manual` (a person confirms it), or
 * `pending` while the run has not reached a finish node.
 */
status: string, detail?: string, };

export type RunGoal = { statement: string, 
/**
 * `goal.enforce: true`: a failed script or marker criterion fails the
 * run.
 */
enforce: boolean, 
/**
 * Whether the criteria were checked (the run reached a finish node).
 */
checked: boolean, criteria: Array<GoalCriterionResult>, passed: number, failed: number, manual: number, };

export type RunStatus = "created" | "running" | "paused" | "succeeded" | "failed" | "aborted" | "interrupted";

export type NodeStatus = "pending" | "ready" | "running" | "succeeded" | "failed" | "unknown" | "timed_out" | "interrupted" | "skipped" | "cancelled";

export type WaitingKind = "human_review" | "wait" | "question" | "supervisor" | "host_task";

export type PendingQuestion = { node: string, question: string, options: Array<string>, 
/**
 * `"human"` or `"supervisor"`, from the node's `answer_by` in the run's
 * playbook snapshot. Defaults to `"human"` when the snapshot or node is
 * missing (fail safe, same default as `question::answer_by_for`).
 */
answer_by: string, 
/**
 * Milliseconds since epoch when the question was asked, taken from the
 * matching `QuestionAsked` event's `ts` when drive has journaled it.
 * `0` before that (the channel entry exists but drive has not yet
 * observed it); the web treats `0` as "just now" rather than
 * synthesizing a non-deterministic clock reading here.
 */
asked_at: number, };

export type PendingHostTask = { 
/**
 * The run the task belongs to: the run itself, or a sub-playbook child
 * run it started (a child inherits its parent's host). Submit with this
 * id or the parent's.
 */
run_id: string, task_id: string, node: string, attempt: number, 
/**
 * The task for the subagent: the rendered node prompt, the report
 * contract included.
 */
prompt: string, 
/**
 * The subagent's system context (the profile's role prompt), when the
 * profile has one.
 */
role_prompt: string | null, 
/**
 * Paths of the skills the subagent should load.
 */
skills: Array<string>, 
/**
 * The directory the subagent works in.
 */
workdir: string, 
/**
 * The node's declared `outputs` contract, if any.
 */
outputs: unknown, 
/**
 * Wall-clock milliseconds by which the task must be submitted.
 */
deadline: number | null, 
/**
 * The model a fallback entry or tier routing asks for (a hint).
 */
model_hint: string | null, 
/**
 * Environment variables to set for the subagent.
 */
env: { [key in string]: string }, 
/**
 * Milliseconds since epoch when the task was requested.
 */
requested_at: number, };

export type ReviewRecommendation = { 
/**
 * One of the gate's options.
 */
option: string, p: number, confidence: number, provider: string, model: string, calibrated: boolean, 
/**
 * The engine posted this option as the decision itself (enforce,
 * `auto_decide`, Part 14.4).
 */
applied?: boolean, };

export type PendingReview = { node: string, 
/**
 * The gate node's title from the playbook, when it has one.
 */
title?: string, 
/**
 * A single self-contained owner-facing line: names the gate, its options,
 * and how to decide. This is the text a supervising agent relays verbatim.
 */
instruction: string, 
/**
 * The configured decisions (for a structured UI); empty falls back to
 * approve/reject in the instruction text.
 */
options: Array<string>, 
/**
 * The decision mechanics alone (apb review CLI / review_decide MCP tool),
 * for callers that render options and mechanics separately.
 */
how_to_decide: string, 
/**
 * Optional guidance from the node's `prompt` (issue #102.9), for callers
 * that render it separately from `instruction` (the web review panel
 * shows it above the options). Already folded into `instruction` too.
 * Template placeholders inside are NOT rendered - literal text.
 */
prompt?: string, 
/**
 * The decision model's advisory recommendation for this visit (issue
 * #165 Part 11), from the open `review_requested`; already appended to
 * `instruction` as one sentence. Never preselected.
 */
recommendation?: ReviewRecommendation, };

export type PendingSupervisor = { node: string, 
/**
 * `"node_failed"` or `"node_timeout"`, matching `WakeTrigger` serde names.
 */
trigger: string, 
/**
 * Self-contained line naming the wake, the failed node, the options, and
 * how to decide.
 */
instruction: string, options: Array<string>, how_to_decide: string, };

export type ProgressSummary = { percent: number, label: string | null, waiting_on: string | null, 
/**
 * The kind of node the run is waiting on when `waiting_on` is set.
 * `None` whenever `waiting_on` is `None`. Feeds the web badge copy
 * (spec section 6 wants distinct texts).
 */
waiting_kind: WaitingKind | null, 
/**
 * The pending question when `waiting_kind == Some(WaitingKind::Question)`.
 * `None` otherwise, and `None` for the plain `compute`/`compute_with`
 * path (no run dir to read the channel files from) - only the
 * `from_run_dir` family populates it.
 */
pending_question: PendingQuestion | null, 
/**
 * The pending human-review gate when `waiting_kind ==
 * Some(WaitingKind::HumanReview)` (issue #42 finding 4). Populated by the
 * pure `compute_with` fold (it needs only events plus the playbook), so
 * unlike `pending_question` it is present on the `compute`/`compute_with`
 * path too. `None` whenever the run is not waiting on a gate.
 */
pending_review: PendingReview | null, 
/**
 * The pending supervisor decision when `waiting_kind ==
 * Some(WaitingKind::Supervisor)` (issue #45 finding 4). Populated by the
 * pure fold from the event log alone.
 */
pending_supervisor: PendingSupervisor | null, 
/**
 * Every human-review gate currently waiting for a decision, in playbook
 * order. Parallel branches can park on several at once; the singular
 * `pending_review` names only the one `waiting_on` points at. The
 * dashboard renders a decision panel per entry.
 */
pending_reviews: Array<PendingReview>, 
/**
 * Every interactive node with an unanswered question, in playbook order
 * (read from the channel files, so only the `from_run_dir` family fills
 * it). The singular `pending_question` is the first of these.
 */
pending_questions: Array<PendingQuestion>, 
/**
 * Every `wait` node currently blocking on its timer or webhook, in
 * playbook order.
 */
pending_waits: Array<string>, 
/**
 * Host execution mode (0.23.0): every host task waiting for the host
 * session, in request order, prompts inline (read from the run
 * directory, so only the `from_run_dir` family fills it).
 * Absent when empty, so a run without host tasks serializes as before.
 */
pending_tasks?: Array<PendingHostTask>, 
/**
 * Deterministic identity of the work plan behind this percent (spec
 * section 3): the playbook version bound to the run plus the latest
 * reported `total` of each cyclic group. It changes exactly when a report
 * raises or lowers a group's total, or the run migrates to a patched
 * version; it does NOT change on ordinary `done`/`label` updates. The web
 * uses it as the monotonicity reset signal, never the display `label`.
 */
plan_key: string, };

export type ChildRun = { node_id: string, run_id: string, 
/**
 * The child's reported status, or `unknown` when its run directory is
 * gone or unreadable.
 */
status: string, };

export type RunUsage = { 
/**
 * Attempts whose output reported usage. Attempts that reported none
 * (plain-text agents, attempts that died) are not in the totals.
 */
attempts: number, input_tokens: number, output_tokens: number, cache_read_tokens: number, cache_write_tokens: number, 
/**
 * The sum of the costs the agent CLIs reported, absent when none did.
 */
cost_usd?: number, 
/**
 * How many of `attempts` reported a cost, so a partial sum reads as one.
 */
cost_attempts: number, 
/**
 * At least one attempt's numbers are apb's own estimate rather than a
 * count the agent CLI printed (`source: estimated`).
 */
estimated?: boolean, 
/**
 * Every attempt the run finished, with or without usage, so a line
 * can say "5 attempts, 3 with usage" instead of passing the reporting
 * ones off as all of them.
 */
finished_attempts: number, };

export type RunDecisions = { 
/**
 * Decisions journaled: answered, failed, or skipped for the budget.
 */
decisions: number, 
/**
 * Requests actually sent to a provider.
 */
requests: number, 
/**
 * Decisions answered without a request (the run's cache).
 */
replayed: number, errors: number, 
/**
 * Provider-reported cost, or the list-price estimate where the
 * provider reported none (then `cost_estimated`).
 */
cost_usd: number, cost_estimated: boolean, 
/**
 * Over the requests actually sent; absent when none was.
 */
p50_latency_ms?: number, p95_latency_ms?: number, by_use: { [key in string]: RunDecisionUse }, };

export type RunDecisionUse = { requests: number, errors: number, 
/**
 * Decisions that changed engine behaviour (never in shadow).
 */
applied: number, 
/**
 * Shadow decisions whose answer a higher mode would have acted on.
 */
shadow_would_change: number, };

export type Rate = { count: number, of: number, rate?: number, };

export type PerRun = { total: number, runs: number, per_run?: number, };

export type Waits = { count: number, median_ms?: number, max_ms?: number, };

export type Outcomes = { succeeded: number, failed: number, aborted: number, 
/**
 * Still running, paused, or ended without a terminal event.
 */
other: number, };

export type Spend = { 
/**
 * Runs whose attempts reported usage.
 */
runs_with_usage: number, 
/**
 * Input plus output tokens (cache reads and writes not included).
 */
tokens: PerRun, 
/**
 * Runs that reported a cost.
 */
runs_with_cost: number, cost_usd: number, cost_per_run_usd?: number, };

export type GoalStats = { index: number, description: string, 
/**
 * `script`, `marker` or `manual`.
 */
check: string, 
/**
 * Runs that checked it.
 */
checked: number, passed: Rate, failed: number, 
/**
 * `error`: the check could not run.
 */
errors: number, manual: number, };

export type NodeStats = { node: string, 
/**
 * Runs the node started in.
 */
runs: number, 
/**
 * Runs where the node's first result was a success on attempt 1, with
 * no retry, fallback or later re-entry.
 */
first_pass: Rate, retries: number, fallbacks: number, 
/**
 * Starts after the first in the same run (a loop back into it).
 */
reentries: number, duration: Waits, 
/**
 * The declared `expected_duration`, in seconds.
 */
expected_s?: number, 
/**
 * Finished executions that took longer than `expected_s`.
 */
over_expected?: Rate, deliverable_missing: number, output_fields_missing: number, };

export type VersionStats = { playbook: string, version: string, runs: number, outcomes: Outcomes, 
/**
 * Succeeded runs over finished runs (succeeded, failed, aborted).
 */
success: Rate, 
/**
 * Succeeded runs with no retry, fallback or loop traversal, over
 * finished runs.
 */
first_pass: Rate, retries: PerRun, fallbacks: PerRun, loop_traversals: PerRun, gate_wait: Waits, question_wait: Waits, 
/**
 * Run start to its terminal event.
 */
duration: Waits, spend: Spend, deliverable_missing: number, output_fields_missing: number, 
/**
 * Empty when the runs checked no goal.
 */
goal: Array<GoalStats>, nodes: Array<NodeStats>, note?: string, };

export type Comparison = { playbook: string, base: string, 
/**
 * `None` when no other version of the playbook has runs.
 */
against?: string, success_delta?: number, first_pass_delta?: number, retries_per_run_delta?: number, loops_per_run_delta?: number, median_duration_delta_ms?: number, cost_per_run_delta_usd?: number, };

export type StatsReport = { runs: number, 
/**
 * By playbook id, then version (oldest first).
 */
versions: Array<VersionStats>, compare?: Comparison, 
/**
 * [`NO_RUNS`] when no run matched.
 */
note?: string, };

export type UsageSource = "reported" | "estimated";

export type AgentUsage = { 
/**
 * Input tokens neither read from nor written to the prompt cache.
 */
input_tokens: number, 
/**
 * Output tokens, reasoning included.
 */
output_tokens: number, cache_read_tokens: number, cache_write_tokens: number, 
/**
 * The attempt's cost in US dollars, only when the CLI printed a
 * non-zero one (a subscription plan prints `0`, which is not a price).
 */
cost_usd?: number, source: UsageSource, };

export type RunSummary = { run_id: string, playbook: string, status: string, started_ts: number, progress?: ProgressSummary, parent_run?: string | null, continued_from?: string | null, superseded_by?: string | null, 
/**
 * The run has a drive claim and that claim's process is provably gone: the
 * journal still reads `running` because the only thing that writes a
 * terminal event is the drive loop that no longer exists. The single-run
 * surfaces (`run_status`, `apb doctor --run`) have answered this for a
 * while; a listing could not, so a killed driver looked healthy in a table.
 * `false` also covers "no drive claim at all", which is not a problem.
 */
driver_dead?: boolean, 
/**
 * Events of a type this binary does not know, skipped when the journal
 * was read: a newer apb wrote them. Zero (and absent) for a journal this
 * binary reads in full.
 */
unknown_events?: number, };

export type RunListEntry = { 
/**
 * Owning project (global dashboard). Empty on the pinned-root test server.
 */
workspace_id: string, project: string, run_id: string, playbook: string, status: string, started_ts: number, progress?: ProgressSummary, parent_run?: string | null, continued_from?: string | null, superseded_by?: string | null, 
/**
 * The run has a drive claim and that claim's process is provably gone: the
 * journal still reads `running` because the only thing that writes a
 * terminal event is the drive loop that no longer exists. The single-run
 * surfaces (`run_status`, `apb doctor --run`) have answered this for a
 * while; a listing could not, so a killed driver looked healthy in a table.
 * `false` also covers "no drive claim at all", which is not a problem.
 */
driver_dead?: boolean, 
/**
 * Events of a type this binary does not know, skipped when the journal
 * was read: a newer apb wrote them. Zero (and absent) for a journal this
 * binary reads in full.
 */
unknown_events?: number, };

export type RunDetail = { run_id: string, playbook: string, version: string, run_status: RunStatus, 
/**
 * Why a failed run ended (`node \`x\`: reason`); null unless failed.
 */
failure_reason: string | null, 
/**
 * Whether a process really drives the run; null when nothing claims to.
 */
driver_alive: boolean | null, 
/**
 * Per-node reported status (`lost` and `interrupted` included).
 */
nodes: { [key in string]: string }, outputs: { [key in string]: string }, instruction: string | null, params: { [key in string]: string }, 
/**
 * The run's working tree (issue #67 item 8), once resolved; null means
 * the nodes run in the project root.
 */
worktree: string | null, 
/**
 * The run's playbook snapshot; null for very old runs without one.
 */
model: { id: string; name: string; nodes: PlaybookNode[]; edges: PlaybookEdge[]; defaults?: { on_failure?: string } | null } | null, layout: WfLayout | null, hooks: { [key in string]: string }, 
/**
 * Sub-runs started by a `playbook` node, one per `ChildRunStarted`.
 */
children: Array<ChildRun>, 
/**
 * The playbook's goal with each criterion's result (C1); absent for a
 * playbook without a goal.
 */
goal?: RunGoal, 
/**
 * The commits the run's nodes made on a git tree (C7); empty when none.
 */
commits?: Array<NodeCommits>, 
/**
 * Progress and every open gate (reviews, questions, waits, supervisor):
 * the run page renders its panels from this, never from `events`.
 */
progress: ProgressSummary | null, answer: string | null, 
/**
 * Token usage the run's attempts reported; null when none did.
 */
usage: RunUsage | null, 
/**
 * Decision-model totals (issue #165 Part 4); absent when the run
 * journaled no decision. Each decision itself is a `decision_made` in
 * `events`.
 */
decisions?: RunDecisions, 
/**
 * Events of a type this binary does not know (a newer apb wrote them),
 * left out of `events`; 0 for a journal read in full.
 */
unknown_events: number, 
/**
 * Who executes the run's agent steps, from its manifest: `cli` (the
 * profiles' CLIs) or `host` (the host session's subagents). Read-only.
 */
execution: "cli" | "host", 
/**
 * A `cli` run whose steps fall back to host tasks when no CLI can start.
 */
execution_fallback: boolean, events: WfEvent[], };

export type TrashEntry = { 
/**
 * The trash folder name `<id>-<deleted_at_ms>`: the exact handle a
 * restore takes when one id was deleted more than once.
 */
name: string, 
/**
 * The playbook id it restores to.
 */
id: string, 
/**
 * When it was deleted, in Unix milliseconds.
 */
deleted_at_ms: number, 
/**
 * Its versions in semver order; a restore brings all of them back.
 */
versions: Array<string>, 
/**
 * The version its `current` pointer names, if any.
 */
current: string | null, 
/**
 * A playbook with this id exists again, so a restore would be refused
 * until that one is deleted.
 */
conflict: boolean, };

export type RestoredPlaybook = { id: string, 
/**
 * The trash entry it came from.
 */
name: string, 
/**
 * The restored `current` version (its digest is now approved).
 */
current: string | null, versions: Array<string>, };

export type TrashListEntry = { 
/**
 * Owning project (global dashboard). Empty on the pinned-root test server.
 */
workspace_id: string, project: string, 
/**
 * The trash folder name `<id>-<deleted_at_ms>`: the exact handle a
 * restore takes when one id was deleted more than once.
 */
name: string, 
/**
 * The playbook id it restores to.
 */
id: string, 
/**
 * When it was deleted, in Unix milliseconds.
 */
deleted_at_ms: number, 
/**
 * Its versions in semver order; a restore brings all of them back.
 */
versions: Array<string>, 
/**
 * The version its `current` pointer names, if any.
 */
current: string | null, 
/**
 * A playbook with this id exists again, so a restore would be refused
 * until that one is deleted.
 */
conflict: boolean, };

export type TrustKind = "playbook" | "profile_bundle" | "connector" | "connector_account";

export type OriginKind = "bundled" | "agent_generated" | "locally_approved" | "repository_provided";

export type TrustEntry = { 
/**
 * The approved content digest (`sha256:<hex>`).
 */
digest: string, 
/**
 * What it approves: a playbook id, a profile name, a connector name, or
 * `connector/account`.
 */
id: string, kind: TrustKind, origin_kind: OriginKind, 
/**
 * When it was approved, in Unix milliseconds.
 */
approved_at_ms: number, };

export type TrustRevoked = { revoked: Array<TrustEntry>, };
