// GENERATED by apb-server's ts_contract test from the Rust types and
// constants. Do not edit: change the Rust side and run
// `APB_WRITE_TS=1 cargo test -p apb-server --lib ts_contract`.

import type { PlaybookEdge, PlaybookNode, WfEvent, WfLayout } from './types'

export type RunStatus = "created" | "running" | "paused" | "succeeded" | "failed" | "aborted" | "interrupted";

export type NodeStatus = "pending" | "ready" | "running" | "succeeded" | "failed" | "unknown" | "timed_out" | "interrupted" | "skipped" | "cancelled";

export type WaitingKind = "human_review" | "wait" | "question" | "supervisor";

export type PendingQuestion = { node: string, question: string, options: Array<string>, 
/**
 * `"human"` or `"supervisor"`, from the node's `answer_by` in the run's
 * playbook snapshot. Defaults to `"human"` when the snapshot or node is
 * missing (fail safe, same default as `question::answer_by_for`).
 */
answer_by: string, 
/**
 * Milliseconds since epoch when the question was asked, taken from the
 * matching `QuestionAsked` event's `ts` when drive has journaled it.
 * `0` before that (the channel entry exists but drive has not yet
 * observed it); the web treats `0` as "just now" rather than
 * synthesizing a non-deterministic clock reading here.
 */
asked_at: number, };

export type PendingReview = { node: string, 
/**
 * The gate node's title from the playbook, when it has one.
 */
title?: string, 
/**
 * A single self-contained owner-facing line: names the gate, its options,
 * and how to decide. This is the text a supervising agent relays verbatim.
 */
instruction: string, 
/**
 * The configured decisions (for a structured UI); empty falls back to
 * approve/reject in the instruction text.
 */
options: Array<string>, 
/**
 * The decision mechanics alone (apb review CLI / review_decide MCP tool),
 * for callers that render options and mechanics separately.
 */
how_to_decide: string, 
/**
 * Optional guidance from the node's `prompt` (issue #102.9), for callers
 * that render it separately from `instruction` (the web review panel
 * shows it above the options). Already folded into `instruction` too.
 * Template placeholders inside are NOT rendered - literal text.
 */
prompt?: string, };

export type PendingSupervisor = { node: string, 
/**
 * `"node_failed"` or `"node_timeout"`, matching `WakeTrigger` serde names.
 */
trigger: string, 
/**
 * Self-contained line naming the wake, the failed node, the options, and
 * how to decide.
 */
instruction: string, options: Array<string>, how_to_decide: string, };

export type ProgressSummary = { percent: number, label: string | null, waiting_on: string | null, 
/**
 * The kind of node the run is waiting on when `waiting_on` is set.
 * `None` whenever `waiting_on` is `None`. Feeds the web badge copy
 * (spec section 6 wants distinct texts).
 */
waiting_kind: WaitingKind | null, 
/**
 * The pending question when `waiting_kind == Some(WaitingKind::Question)`.
 * `None` otherwise, and `None` for the plain `compute`/`compute_with`
 * path (no run dir to read the channel files from) - only the
 * `from_run_dir` family populates it.
 */
pending_question: PendingQuestion | null, 
/**
 * The pending human-review gate when `waiting_kind ==
 * Some(WaitingKind::HumanReview)` (issue #42 finding 4). Populated by the
 * pure `compute_with` fold (it needs only events plus the playbook), so
 * unlike `pending_question` it is present on the `compute`/`compute_with`
 * path too. `None` whenever the run is not waiting on a gate.
 */
pending_review: PendingReview | null, 
/**
 * The pending supervisor decision when `waiting_kind ==
 * Some(WaitingKind::Supervisor)` (issue #45 finding 4). Populated by the
 * pure fold from the event log alone.
 */
pending_supervisor: PendingSupervisor | null, 
/**
 * Every human-review gate currently waiting for a decision, in playbook
 * order. Parallel branches can park on several at once; the singular
 * `pending_review` names only the one `waiting_on` points at. The
 * dashboard renders a decision panel per entry.
 */
pending_reviews: Array<PendingReview>, 
/**
 * Every interactive node with an unanswered question, in playbook order
 * (read from the channel files, so only the `from_run_dir` family fills
 * it). The singular `pending_question` is the first of these.
 */
pending_questions: Array<PendingQuestion>, 
/**
 * Every `wait` node currently blocking on its timer or webhook, in
 * playbook order.
 */
pending_waits: Array<string>, 
/**
 * Deterministic identity of the work plan behind this percent (spec
 * section 3): the playbook version bound to the run plus the latest
 * reported `total` of each cyclic group. It changes exactly when a report
 * raises or lowers a group's total, or the run migrates to a patched
 * version; it does NOT change on ordinary `done`/`label` updates. The web
 * uses it as the monotonicity reset signal, never the display `label`.
 */
plan_key: string, };

export type ChildRun = { node_id: string, run_id: string, 
/**
 * The child's reported status, or `unknown` when its run directory is
 * gone or unreadable.
 */
status: string, };

export type RunUsage = { 
/**
 * Attempts whose output reported usage. Attempts that reported none
 * (plain-text agents, attempts that died) are not in the totals.
 */
attempts: number, input_tokens: number, output_tokens: number, cache_read_tokens: number, cache_write_tokens: number, 
/**
 * The sum of the costs the agent CLIs reported, absent when none did.
 */
cost_usd?: number, 
/**
 * How many of `attempts` reported a cost, so a partial sum reads as one.
 */
cost_attempts: number, 
/**
 * At least one attempt's numbers are the CLI's own count rather than
 * the provider's (`source: estimated`).
 */
estimated?: boolean, };

export type UsageSource = "reported" | "estimated";

export type AgentUsage = { 
/**
 * Input tokens neither read from nor written to the prompt cache.
 */
input_tokens: number, 
/**
 * Output tokens, reasoning included.
 */
output_tokens: number, cache_read_tokens: number, cache_write_tokens: number, 
/**
 * The attempt's cost in US dollars, only when the CLI printed a
 * non-zero one (a subscription plan prints `0`, which is not a price).
 */
cost_usd?: number, source: UsageSource, };

export type RunSummary = { run_id: string, playbook: string, status: string, started_ts: number, progress?: ProgressSummary, parent_run?: string | null, continued_from?: string | null, superseded_by?: string | null, 
/**
 * The run has a drive claim and that claim's process is provably gone: the
 * journal still reads `running` because the only thing that writes a
 * terminal event is the drive loop that no longer exists. The single-run
 * surfaces (`run_status`, `apb doctor --run`) have answered this for a
 * while; a listing could not, so a killed driver looked healthy in a table.
 * `false` also covers "no drive claim at all", which is not a problem.
 */
driver_dead?: boolean, 
/**
 * Events of a type this binary does not know, skipped when the journal
 * was read: a newer apb wrote them. Zero (and absent) for a journal this
 * binary reads in full.
 */
unknown_events?: number, };

export type RunListEntry = { 
/**
 * Owning project (global dashboard). Empty on the pinned-root test server.
 */
workspace_id: string, project: string, run_id: string, playbook: string, status: string, started_ts: number, progress?: ProgressSummary, parent_run?: string | null, continued_from?: string | null, superseded_by?: string | null, 
/**
 * The run has a drive claim and that claim's process is provably gone: the
 * journal still reads `running` because the only thing that writes a
 * terminal event is the drive loop that no longer exists. The single-run
 * surfaces (`run_status`, `apb doctor --run`) have answered this for a
 * while; a listing could not, so a killed driver looked healthy in a table.
 * `false` also covers "no drive claim at all", which is not a problem.
 */
driver_dead?: boolean, 
/**
 * Events of a type this binary does not know, skipped when the journal
 * was read: a newer apb wrote them. Zero (and absent) for a journal this
 * binary reads in full.
 */
unknown_events?: number, };

export type RunDetail = { run_id: string, playbook: string, version: string, run_status: RunStatus, 
/**
 * Why a failed run ended (`node \`x\`: reason`); null unless failed.
 */
failure_reason: string | null, 
/**
 * Whether a process really drives the run; null when nothing claims to.
 */
driver_alive: boolean | null, 
/**
 * Per-node reported status (`lost` and `interrupted` included).
 */
nodes: { [key in string]: string }, outputs: { [key in string]: string }, instruction: string | null, params: { [key in string]: string }, 
/**
 * The run's working tree (issue #67 item 8), once resolved; null means
 * the nodes run in the project root.
 */
worktree: string | null, 
/**
 * The run's playbook snapshot; null for very old runs without one.
 */
model: { id: string; name: string; nodes: PlaybookNode[]; edges: PlaybookEdge[]; defaults?: { on_failure?: string } | null } | null, layout: WfLayout | null, hooks: { [key in string]: string }, 
/**
 * Sub-runs started by a `playbook` node, one per `ChildRunStarted`.
 */
children: Array<ChildRun>, 
/**
 * Progress and every open gate (reviews, questions, waits, supervisor):
 * the run page renders its panels from this, never from `events`.
 */
progress: ProgressSummary | null, answer: string | null, 
/**
 * Token usage the run's attempts reported; null when none did.
 */
usage: RunUsage | null, 
/**
 * Events of a type this binary does not know (a newer apb wrote them),
 * left out of `events`; 0 for a journal read in full.
 */
unknown_events: number, events: WfEvent[], };

export type TrashEntry = { 
/**
 * The trash folder name `<id>-<deleted_at_ms>`: the exact handle a
 * restore takes when one id was deleted more than once.
 */
name: string, 
/**
 * The playbook id it restores to.
 */
id: string, 
/**
 * When it was deleted, in Unix milliseconds.
 */
deleted_at_ms: number, 
/**
 * Its versions in semver order; a restore brings all of them back.
 */
versions: Array<string>, 
/**
 * The version its `current` pointer names, if any.
 */
current: string | null, 
/**
 * A playbook with this id exists again, so a restore would be refused
 * until that one is deleted.
 */
conflict: boolean, };

export type RestoredPlaybook = { id: string, 
/**
 * The trash entry it came from.
 */
name: string, 
/**
 * The restored `current` version (its digest is now approved).
 */
current: string | null, versions: Array<string>, };

export type TrashListEntry = { 
/**
 * Owning project (global dashboard). Empty on the pinned-root test server.
 */
workspace_id: string, project: string, 
/**
 * The trash folder name `<id>-<deleted_at_ms>`: the exact handle a
 * restore takes when one id was deleted more than once.
 */
name: string, 
/**
 * The playbook id it restores to.
 */
id: string, 
/**
 * When it was deleted, in Unix milliseconds.
 */
deleted_at_ms: number, 
/**
 * Its versions in semver order; a restore brings all of them back.
 */
versions: Array<string>, 
/**
 * The version its `current` pointer names, if any.
 */
current: string | null, 
/**
 * A playbook with this id exists again, so a restore would be refused
 * until that one is deleted.
 */
conflict: boolean, };

export type TrustKind = "playbook" | "profile_bundle" | "connector" | "connector_account";

export type OriginKind = "bundled" | "agent_generated" | "locally_approved" | "repository_provided";

export type TrustEntry = { 
/**
 * The approved content digest (`sha256:<hex>`).
 */
digest: string, 
/**
 * What it approves: a playbook id, a profile name, a connector name, or
 * `connector/account`.
 */
id: string, kind: TrustKind, origin_kind: OriginKind, 
/**
 * When it was approved, in Unix milliseconds.
 */
approved_at_ms: number, };

export type TrustRevoked = { revoked: Array<TrustEntry>, };
