// GENERATED by apb-server's ts_contract test from the Rust types and
// constants. Do not edit: change the Rust side and run
// `APB_WRITE_TS=1 cargo test -p apb-server --lib ts_contract`.

/** The playbook schema this apb writes. */
export const CURRENT_SCHEMA = 2

/** Every node `type` tag. */
export const NODE_TYPES = ['start', 'agent_task', 'script', 'prompt', 'condition', 'human_review', 'wait', 'finish', 'playbook', 'judge'] as const
export type NodeType = (typeof NODE_TYPES)[number]

/** The decisions a human_review gate without options offers. */
export const DEFAULT_REVIEW_OPTIONS = ['approve', 'reject'] as const

/** The dashboard's default port (the dev server proxies to it). */
export const DEFAULT_PORT = 7321

/** Legacy agent ids and the built-in agent each stands for. */
export const AGENT_ALIASES: Readonly<Record<string, string>> = { 'claude-code': 'claude' }

/** Starter document for a new playbook. */
export const NEW_PLAYBOOK_TEMPLATE = "schema: 2\nid: new-playbook\nname: New Playbook\nversion: 0.1.0\n\nnodes:\n  - id: start\n    type: start\n    title: Start\n  - id: done\n    type: finish\n    outcome: success\n\nedges:\n  - { from: start, to: done }\n"
